name: Update Content

on:
  push:
    branches:
      - main
      - docs

jobs:
  update-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pdoc autopep8
          pip install -e .

      - name: Pep8ify
        run: |
          autopep8 data_request_api --max-line-length=120 --experimental --recursive --in-place --pep8-passes 2000 --verbose

      - name: Tech documentation generation
        run: |
          pdoc --html data_request_api/stable --output-dir docs/ --force

      - name: Commit All
        uses: WCRP-CMIP/CMIP-LD/actions/commit-all@main
        with:
          message: "Automated Content Update"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/CMIP-Data-Request/CMIP7_DReq_Software.git
          git push
